### ISSUE TITLE
Cookie-Layer: Anpassungen

### ISSUE THREAD

**Issue by bclausdorff** [codeforhamburg/codeforhamburg.github.io#10]
- [ ] Vor allem für kleine Bildschirme sollte der Text kurz gehalten werden (siehe Bild)
- [ ] Im Text wird ausschließlich der Newsletter erwähnt. Zum Newsletter werden aber eigentlich gar keine Cookies erhoben, oder? Wo Cookies erhoben werden sind Google Analytics und evtl. Twitter. Darauf muss aber gar nicht genauer eingegangen werden. Es reicht lediglich die kurze Infos, dass Cookies erhoben werden. Welche das sind, kann der Nutzer bei Interesse dann unter dem Link nachlesen.
- [ ] Es sollte einen Hinweis geben, dass man unter dem Link Möglichkeiten zur Widersprechung findet
- [ ] Der Button sollte mit einer Zustimmung beschriftet sein wie "Akzeptieren", so dass der Nutzer weiß, dass er mit dem Klicken der Nutzung von Cookies zustimmt.
- [ ] Evtl. die dunkle Variante des Cookie-Layer verwenden, damit sich der Layer besser vom Rest der Seite abhebt?
- [ ] Evtl. unten positionieren, damit die Layer das Menu nicht überdeckt (siehe #9)

![small screen](https://cloud.githubusercontent.com/assets/17184113/15096534/76e75f84-14fd-11e6-9797-99420844d245.PNG)

**Comment by lundelius** [comment]
überarbeitet
