### ISSUE TITLE
Transparentes favicon

### ISSUE THREAD

**Issue by lundelius** [codeforhamburg/codeforhamburg.github.io#16]
Hier die SVG... kann das jemand übernehmen der 3 min mehr Photoshop/Illustrator-Erfahrung hat als ich? ;-)

http://hexb.in/vector/CodeForHamburg.svg

oder als PNG
http://hexb.in/hexagons/CodeForHamburg.png

Lieben Dank!

**Comment by webisdead** [comment]
Finds n bisschen arg kleinteilig für ein Fav. Gegenvorschlag? Oder gibts da irgendwelche Legal-Geschichten? Baue es dann auch gleich ein.
![bildschirmfoto 2016-05-11 um 10 53 00](https://cloud.githubusercontent.com/assets/6973876/15175437/8b731f04-1766-11e6-8246-66c69c6f422a.png)

**Comment by lundelius** [comment]
ja, fand ich auch! Aber in der Not...Hatte es durch nen favicon-generator gemuddelt ;-)

Danke fürs schönere Nachpinseln!

Kannst Du gerne einbauen - gibt keine Regeln die uns da behindern...
