### ISSUE TITLE
Travis.CI failed...

### ISSUE THREAD

**Issue by lundelius** [codeforhamburg/codeforhamburg.github.io#17]
Wir haben irgendwas kaputt gemacht - wissen aber nicht was...

Fehlermeldung beim Start des Jekyll-Servers (lokal):
/Users/timo/.rvm/gems/ruby-2.2.2/gems/liquid-2.6.1/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"

Siehe weitere Infos:
https://travis-ci.org/codeforhamburg/codeforhamburg.github.io/builds/129357425

Anscheinend muss die scripts/test angepasst werden?!

`The command "scripts/test" exited with 34.
Done. Your build exited with 1.`

**Comment by webisdead** [comment]
@lundelius 
Ein Update des gems genügte: "bundle update github-pages". Oder du mergst https://github.com/webisdead/codeforhamburg.github.io/commit/bb37bea90c38aa2b32e2278a1749880a8bdc1aa1 hinein.

Zusätzlich werden in deinem Fall 34 Warnings generiert - die gilt es zu beheben. Dann sollte auch der Build klappen.

Dazu ein Super Chrome-Plugin: https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb

Ich denke mal, da ihr "verwaltungsnah" seid, ist Accessibility auf jeden Fall ein Thema oder? Sonst könnte man das auch einfach ausknipsen.

**Comment by lundelius** [comment]
ich hab deinen erwähnten Commit webisdead@bb37bea gemerged... aber so richtig hat das noch nicht funktioniert. Trotzdem: krass was da noch alles zu kam :-)

Und: Danke für den Plugin-Tipp. Ja, dass Thema Accessibility ist relevant - wir brauchen da aber noch etwas Erfahrung. Nun wissen wir zumindest was alles falsch bzw. richtig läuft!

**Comment by lundelius** [comment]
@webisdead ist nun (schon bisschen länger her) gefixt! 

Danke für die neue Depencies-Liste
