### ISSUE TITLE
Blogging Post 2016

### ISSUE THREAD

**Issue by JulesTea** [codeforhamburg/codeforhamburg.github.io#27]
Ich habe eine neues Dokument "FOS 19 Announcement" unter: _posts/blog erstellt, leider wird es nicht auf der Webseite angezeigt. Wo soll der Text gepostet werden damit er direkt auf der Webseite angezeigt wird?

**Comment by bclausdorff** [comment]
Ich gehe davon aus, dass im Post noch die Metadaten im Kopfteil fehlen.

Wenn Du Dir z.B. den letzten Post anguckst, sind da noch zusätzliche Informationen enthalten.

Wenn Du die in deinen Post überträgst und anpasst, dürfte das mit der Veröffentlichung klappen. 

**Beispiel**

```
---
layout: blog
author: timo_lundelius
published: true
title: "Release Party - Fr, 20. Mai - 18 Uhr | Betahaus"
tags: "Release-Party"
---
```

https://raw.githubusercontent.com/codeforhamburg/codeforhamburg.github.io/master/_posts/blog/2016-05-10-release-party-fr-20-mai-18-uhr-betahaus.md

**Comment by bclausdorff** [comment]
Der "Blog" wurde anscheinend mal deaktiviert: https://github.com/codeforhamburg/codeforhamburg.github.io/commit/60ddd6ad98f658e1f6102b97f39fd09dd1ef69a3
Die Einträge unter `_posts/blog` werden somit aktuell ignoriert.

Die Einträge, die auf [codeforhamburg.org](https://codeforhamburg.org/) zu sehen sind, befinden sich direkt in der `index.html` : 
https://github.com/codeforhamburg/codeforhamburg.github.io/blob/master/index.html
 
Wenn Du Deinen Post dort einfügst (mit HTML statt mit Markdown), dürfte er auf der Webseite zu sehen sein.

**Comment by JulesTea** [comment]
Vielen Dank! Hardcoden hat geklappt! :+1: :rocket:
