### ISSUE TITLE
Was für eine ID muss auf die projekte/index.html?

### ISSUE THREAD

**Issue by lundelius** [codeforhamburg/codeforhamburg.github.io#3]
Hier, Zeile 21:
https://github.com/codeforhamburg/codeforhamburg.github.io/blob/master/projekte/index.html

`<a href="https://github.com/login/oauth/authorize?client_id=**9538d6f0b5da7e2d972e**&scope=repo&redirect_uri=http://prose.io/#{{repository_nwo}}/new/{{default_branch}}/_posts/projects/{{id}}/{{file_name}}" class="btn btn-xs btn-success">Create detailed project page</a></strong><span style="display:none">{{id}}</span>`

**Comment by bclausdorff** [comment]
The one from prose.io.
