### ISSUE TITLE
Trennung von Datenschutzerklärung & Impressum

### ISSUE THREAD

**Issue by lundelius** [codeforhamburg/codeforhamburg.github.io#4]
Trennung von Datenschutzerklärung & Impressum 

sowie Hinzufügen von Google Analytics Erklärung

**Comment by bclausdorff** [comment]
https://www.e-recht24.de/muster-datenschutzerklaerung.html

**Comment by lundelius** [comment]
Danke für den Link-tipp! 
datenschutzerklaerung ist eingebaut.
