### ISSUE TITLE
EU - Cookie Layer hinzufügen

### ISSUE THREAD

**Issue by lundelius** [codeforhamburg/codeforhamburg.github.io#5]
Gibts da was fertiges, einfaches?

Gerne gaaaanz nach unten auf die Seite...

**Comment by bclausdorff** [comment]
https://silktide.com/tools/cookie-consent/

**Comment by bclausdorff** [comment]
Empfehlungen von der c't Heft 2016-07 für "Cookie Opt-Out" a.k.a. "stillschweigende Einwilligung":
- [x] das Overlay sollte auffällig und immer sichtbar auf der Seite eingebunden werden
- [ ] das Overlay sollte bereits auf der ersten vom Nutzer besuchten Seite der Webseite zu sehen sein
- [ ] das Overlay sollte erst verschwinden, sobald der Nutzer es weggeklickt hat
- [ ] im Overlay sollte auf eine Widerspruchsmöglichkeit hingewiesen werden
- [ ] das Overlay sollte einen Button / Link aufweisen, mit dem man widersprechen kann bzw. das zu einer Seite führt, auf der man widersprechen kann (z.B. in den Datenschutzbestimmungen)

**Comment by lundelius** [comment]
eingebaut! @bclausdorff Danke für den silktide tipp!
Datenschutzseite folgt... Link bereits gesetzt
