### ISSUE TITLE
Datenschutz: Piwik, Facebook und Google +1 enthalten

### ISSUE THREAD

**Issue by bclausdorff** [codeforhamburg/codeforhamburg.github.io#8]
Aktuell sind im Datenschutz folgende Dienste enthalten, die wir aktuell nicht auf der Seite nutzen:
- Piwik (wir haben schon Google Analytics)
- Facebook
- Google +1

Ist der Einsatz in der Zukunft noch geplant und sind sie deshalb enthalten?
Beim e-recht24.de Datenschutz-Generator kann man die Häkchen wegnehmen.
Dann generiert er einem die ohne.

**Comment by lundelius** [comment]
- Piwik: just in case... ;-)
- Facebook - wir haben da ja ne Seite... denke evtl. schon... irgendwann.
- wenn wir die anderen schon machen, dann nun ne Google+ Orga Seite...
