### ISSUE TITLE
Cookie-Layer überdeckt Menü

### ISSUE THREAD

**Issue by bclausdorff** [codeforhamburg/codeforhamburg.github.io#9]
Aktuell überdeckt die Cookie-Layer das Menü. Somit kann man die Seite nur richtig durchstöbern, wenn man die Cookie-Layer wegklickt. Ist das so gewollt?

**Lösungsansatz**
Evtl. sollte man die Cookie-Layer am unteren Bildschirmrand platzieren?

**Comment by lundelius** [comment]
hat sich mit #10 erledigt und wurde rechts unten positioniert
